### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by joldibaev** [CalebM1987/fernet#1]
![image](https://user-images.githubusercontent.com/44665144/213866861-ad7041ec-ac3e-4c5e-b9ea-b7a2fa4396cd.png)

```
{
	"name": "ax-chat-ts",
	"version": "0.0.0",
	"scripts": {
		"dev": "vite",
		"build": "vue-tsc --noEmit && vite build",
		"preview": "vite preview --port 5050",
		"typecheck": "vue-tsc --noEmit",
		"prettier": "npx prettier --write ."
	},
	"dependencies": {
		"@crmackey/fernet": "^0.0.12",
		"centrifuge": "^2.8.5",
		"vue": "^3.2.45",
		"vue-i18n": "^9.2.2"
	},
	"devDependencies": {
		"@types/node": "^18.11.18",
		"@vitejs/plugin-vue": "^4.0.0",
		"@vue/tsconfig": "^0.1.3",
		"prettier": "2.8.2",
		"sass": "^1.57.1",
		"typescript": "~4.9.4",
		"vite": "^4.0.4",
		"vue-tsc": "^1.0.24"
	}
}
```

```
<script setup lang="ts">
function submitContactForm(e: Event) {

const secret = new Secret("cw_0x689RpI-jtRR7oE8h_eQsKImvJapLeSbXpwF4e4=");
		const token = new Token({secret,});
		const encryptedBody = token.encode(body);
		console.log(encryptedBody);
}
</script>
```

**Comment by CalebM1987** [comment]
This is a known issue that affects the `crypto` library because of its dependence on the native `Buffer`. This is described in this [angular issue](https://github.com/angular/angular-cli/issues/15954) and how it affects `vite` apps is described [here](https://github.com/bevacqua/dragula/issues/602#issuecomment-1109840139). Fortunately, there is an easy way to shim this in `vite` apps by defining `global` in the `vite.config.ts`: 


```ts
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: 'window'
  },
  plugins: [vue()],
})
```

You should just be able to make this change in your `vue` app without needing to pull a newer version of this library.

I appreciate you bringing this to my attention, I have updated the [README](https://github.com/CalebM1987/fernet) to describe this issue and added a [demo](https://github.com/CalebM1987/fernet/tree/main/demo) app (starting at `v.0.0.13`).
